"""Models for AVR Research Formation System."""

from .enums import (
    Phase,
    SessionStatus,
    ConversationState,
    GateResult,
    ViolationSeverity,
    ViolationTier,
    DesignType,
    EndpointType,
    Specialty,
    UserTier,
    MessageRole,
)

from .schemas import (
    ExtractedAttributes,
    ResearchBlueprint,
    Violation,
    ViolationList,
    SessionStartRequest,
    SessionStartResponse,
    ChatMessageRequest,
    ChatMessageResponse,
    SessionDetailResponse,
    SessionListItem,
    JournalSuggestion,
    AbstractGenerateRequest,
    AbstractGenerateResponse,
    GateRunRequest,
    GateRunResponse,
    RevisionExplainRequest,
    RevisionExplainResponse,
    OutlineGenerateRequest,
    OutlineGenerateResponse,
    JournalMetadata,
    OutlineSection,
    ConversationTurn,
    ConversationHistoryResponse,
)

__all__ = [
    # Enums
    "Phase",
    "SessionStatus",
    "ConversationState",
    "GateResult",
    "ViolationSeverity",
    "ViolationTier",
    "DesignType",
    "EndpointType",
    "Specialty",
    "UserTier",
    "MessageRole",
    # Schemas
    "ExtractedAttributes",
    "ResearchBlueprint",
    "Violation",
    "ViolationList",
    "SessionStartRequest",
    "SessionStartResponse",
    "ChatMessageRequest",
    "ChatMessageResponse",
    "SessionDetailResponse",
    "SessionListItem",
    "JournalSuggestion",
    "AbstractGenerateRequest",
    "AbstractGenerateResponse",
    "GateRunRequest",
    "GateRunResponse",
    "RevisionExplainRequest",
    "RevisionExplainResponse",
    "OutlineGenerateRequest",
    "OutlineGenerateResponse",
    "JournalMetadata",
    "OutlineSection",
    "ConversationTurn",
    "ConversationHistoryResponse",
]
